# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 728178ff13db20e96fd27f2ae4839a5c0a25ac49bf381d457fc9900a5b90581396d0c392ddeecd53555e7c8a20d69916a854e0ef9f5952283c64f6a75e0a2415

test:
  secret_key_base: 41e7be3437fed4182dc7db2b27729adb40f86da043c4cde2a3b0eb4dbffff551d368311871fb5afbabaab64cff1b6025e3ce831612889779bd4a28d29075ae5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
